from crawler.shops import (
    akimoba,
    base,
    homura,
    ichiban,
    ichome,
    jcka,
    mix,
    mobaste,
    morimori,
    rakuen,
    rudeya,
    shouten,
    sommelier,
    wiki,
)

SHOPS = {
    "morimori": morimori,
    "ichiban": ichiban,
    "mobaste": mobaste,
    "shouten": shouten,
    "ichome": ichome,
    "mix": mix,
    "akimoba": akimoba,
    "homura": homura,
    "rudeya": rudeya,
    "wiki": wiki,
    "rakuen": rakuen,
    "base": base,
    "sommelier": sommelier,
    "jcka": jcka,
}
